# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import infoshop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(db_index=True, default=False, verbose_name='Опубликовано')),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='Расширенный заголовок')),
                ('menutitle', models.CharField(blank=True, max_length=512, null=True, verbose_name='Заголовок для меню')),
                ('slug', models.SlugField(blank=True, default='', max_length=300, verbose_name='Slug')),
                ('url', models.CharField(blank=True, default='', max_length=300, verbose_name='Url')),
                ('seo_keywords', models.CharField(blank=True, max_length=512, null=True, verbose_name='SEO ключевые слова')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='SEO описание')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Порядок')),
                ('deleted', models.DateTimeField(editable=False, null=True, verbose_name='Удалено')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, default='', max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, default='', upload_to=infoshop.models.make_upload_path, verbose_name='Изображение')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='infoshop.Category', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Тематика',
                'verbose_name_plural': 'Тематики',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Порядок')),
                ('image', models.ImageField(blank=True, default='', upload_to=infoshop.models.make_upload_path, verbose_name='Изображение')),
                ('name', models.CharField(default='', max_length=250, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Порядок')),
                ('deleted', models.DateTimeField(editable=False, null=True, verbose_name='Удалено')),
                ('name', models.CharField(default='', max_length=250, verbose_name='Название')),
                ('description', models.CharField(blank=True, default='', max_length=1000, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Вариант',
                'verbose_name_plural': 'Варианты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(db_index=True, default=False, verbose_name='Опубликовано')),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='Расширенный заголовок')),
                ('menutitle', models.CharField(blank=True, max_length=512, null=True, verbose_name='Заголовок для меню')),
                ('slug', models.SlugField(blank=True, default='', max_length=300, verbose_name='Slug')),
                ('url', models.CharField(blank=True, default='', max_length=300, verbose_name='Url')),
                ('seo_keywords', models.CharField(blank=True, max_length=512, null=True, verbose_name='SEO ключевые слова')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='SEO описание')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Порядок')),
                ('deleted', models.DateTimeField(editable=False, null=True, verbose_name='Удалено')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, default='', max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, default='', upload_to=infoshop.models.make_upload_path, verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='Price')),
                ('promo', models.BooleanField(default=False, help_text='Показывать продукт на главной странице', verbose_name='Промо')),
                ('type_video', models.BooleanField(default=False, verbose_name='Смотреть')),
                ('type_audio', models.BooleanField(default=False, verbose_name='Слушать')),
                ('type_book', models.BooleanField(default=False, verbose_name='Читать')),
                ('type_flow', models.BooleanField(default=False, verbose_name='Участвовать')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='infoshop.Category', verbose_name='Тематика')),
            ],
            options={
                'verbose_name': 'Инфопродукт',
                'verbose_name_plural': 'Инфопродукты',
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='infoshop.Product', verbose_name='Инфопродукт'),
        ),
        migrations.AddField(
            model_name='images',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='infoshop.Product', verbose_name='Инфопродукт'),
        ),
    ]
