# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-12 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import infoshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('infoshop', '0002_auto_20190512_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='wall',
            field=models.ImageField(blank=True, default='', upload_to=infoshop.models.make_upload_path, verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='product',
            name='wall',
            field=models.ImageField(blank=True, default='', upload_to=infoshop.models.make_upload_path, verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=infoshop.models.make_upload_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=infoshop.models.make_upload_path, verbose_name='Изображение'),
        ),
    ]
