# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-12 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoshop', '0004_auto_20190512_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_description',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='SEO описание'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_description',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='SEO описание'),
        ),
    ]
