# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-12 12:37
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoshop', '0005_auto_20190512_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color0',
            field=colorfield.fields.ColorField(default='#333333', max_length=18),
        ),
        migrations.AddField(
            model_name='product',
            name='color1',
            field=colorfield.fields.ColorField(default='#333333', max_length=18),
        ),
        migrations.AddField(
            model_name='product',
            name='color2',
            field=colorfield.fields.ColorField(default='#333333', max_length=18),
        ),
    ]
