# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-18 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import infoshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('infoshop', '0007_auto_20190516_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('accusative', models.CharField(max_length=250, null=True, verbose_name='Винительный падеж')),
                ('dative', models.CharField(max_length=250, null=True, verbose_name='Дательный падеж')),
                ('genitive', models.CharField(max_length=250, null=True, verbose_name='Родительный падеж')),
                ('ablative', models.CharField(max_length=250, null=True, verbose_name='Творительный падеж')),
                ('prepositional', models.CharField(max_length=250, null=True, verbose_name='Предложный падеж')),
            ],
            options={
                'verbose_name': 'Тип инфопродукта',
                'verbose_name_plural': 'Типы инфопродуктов',
            },
        ),
        migrations.RenameField(
            model_name='product',
            old_name='type_audio',
            new_name='media_type_audio',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='type_book',
            new_name='media_type_book',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='type_flow',
            new_name='media_type_flow',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='type_video',
            new_name='media_type_video',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='', upload_to=infoshop.models.make_upload_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='wall',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='', upload_to=infoshop.models.make_upload_path, verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=infoshop.models.make_upload_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='', upload_to=infoshop.models.make_upload_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wall',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='', upload_to=infoshop.models.make_upload_path, verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='infoshop.ProductType', verbose_name='Тип инфопродукта'),
        ),
    ]
