# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-23 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import infoshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('oko_schools', '0001_initial'),
        ('infoshop', '0017_auto_20190519_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oko_schools.Owner', verbose_name='Автор'),
        ),
    ]
