# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-06 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields
import infoshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('infoshop', '0020_auto_20190627_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_menu_authors',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название меню для авторов'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_menu_schools',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название меню для школ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='', upload_to=infoshop.models.make_upload_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='wall',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='', upload_to=infoshop.models.make_upload_path, verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=infoshop.models.make_upload_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='', upload_to=infoshop.models.make_upload_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wall',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='', upload_to=infoshop.models.make_upload_path, verbose_name='Обложка'),
        ),
    ]
