# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-19 07:32
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True, verbose_name='Удалено')),
                ('published', models.BooleanField(db_index=True, default=False, verbose_name='Опубликовано')),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='Расширенный заголовок')),
                ('title_menu', models.CharField(blank=True, max_length=512, null=True, verbose_name='Заголовок для меню')),
                ('slug', models.SlugField(blank=True, default='', max_length=300, verbose_name='Slug')),
                ('url', models.CharField(blank=True, default='', max_length=300, verbose_name='Url')),
                ('seo_keywords', models.CharField(blank=True, max_length=512, null=True, verbose_name='SEO ключевые слова')),
                ('seo_description', models.TextField(blank=True, max_length=512, null=True, verbose_name='SEO описание')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('contact_website', models.CharField(max_length=250, null=True, verbose_name='Официальный сайт')),
                ('contact_partner_site', models.CharField(max_length=250, null=True, verbose_name='Партнерская программа')),
                ('contact_email', models.CharField(max_length=250, null=True, verbose_name='Email')),
                ('contact_post_address', models.CharField(max_length=250, null=True, verbose_name='Почтовый адрес')),
                ('contact_phone', models.CharField(max_length=250, null=True, verbose_name='Контактный телефон')),
                ('contact_skype', models.CharField(max_length=250, null=True, verbose_name='Skype')),
                ('contact_whatsapp', models.CharField(max_length=250, null=True, verbose_name='WhatsApp')),
                ('contact_viber', models.CharField(max_length=250, null=True, verbose_name='Viber')),
                ('contact_telegram', models.CharField(max_length=250, null=True, verbose_name='Telegram')),
                ('social_youtube', models.CharField(max_length=250, null=True, verbose_name='Канал на Youtube')),
                ('social_vk', models.CharField(max_length=250, null=True, verbose_name='Страница Вконтакте')),
                ('social_fb', models.CharField(max_length=250, null=True, verbose_name='Страница Facebook')),
                ('social_instagram', models.CharField(max_length=250, null=True, verbose_name='Страница Instagram')),
                ('social_telegram', models.CharField(max_length=250, null=True, verbose_name='Канал в Telegram')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Имя')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('city', models.CharField(blank=True, max_length=250, null=True, verbose_name='Город')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('owner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authors.Owner')),
                ('name_nominative', models.CharField(max_length=250, null=True, verbose_name='Именительный падеж')),
                ('name_genitive', models.CharField(max_length=250, null=True, verbose_name='Родительный падеж')),
                ('name_dative', models.CharField(max_length=250, null=True, verbose_name='Дательный падеж')),
                ('name_accusative', models.CharField(max_length=250, null=True, verbose_name='Винительный падеж')),
                ('name_ablative', models.CharField(max_length=250, null=True, verbose_name='Творительный падеж')),
                ('name_prepositional', models.CharField(max_length=250, null=True, verbose_name='Предложный падеж')),
                ('education', models.CharField(blank=True, max_length=500, null=True, verbose_name='Образование')),
            ],
            options={
                'abstract': False,
            },
            bases=('authors.owner', models.Model),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('owner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authors.Owner')),
            ],
            options={
                'abstract': False,
            },
            bases=('authors.owner',),
        ),
        migrations.AddField(
            model_name='author',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authors.School', verbose_name='Школа'),
        ),
    ]
