# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-19 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'Школа', 'verbose_name_plural': 'Школы'},
        ),
        migrations.AlterField(
            model_name='owner',
            name='contact_email',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='contact_partner_site',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Партнерская программа'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Контактный телефон'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='contact_post_address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Почтовый адрес'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='contact_skype',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Skype'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='contact_telegram',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='contact_viber',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Viber'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='contact_website',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Официальный сайт'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='contact_whatsapp',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='social_fb',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Страница Facebook'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='social_instagram',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Страница Instagram'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='social_telegram',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Канал в Telegram'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='social_vk',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Страница Вконтакте'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='social_youtube',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Канал на Youtube'),
        ),
    ]
