# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-19 07:50
from __future__ import unicode_literals

import authors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_auto_20190519_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=authors.models.make_upload_path, verbose_name='Изображение'),
        ),
    ]
