# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infoshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(db_index=True, default=False, verbose_name='Опубликовано')),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='Расширенный заголовок')),
                ('menutitle', models.CharField(blank=True, max_length=512, null=True, verbose_name='Заголовок для меню')),
                ('url', models.CharField(blank=True, default='', max_length=300, verbose_name='Url')),
                ('seo_keywords', models.CharField(blank=True, max_length=512, null=True, verbose_name='SEO ключевые слова')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='SEO описание')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Порядок')),
                ('slug', models.CharField(blank=True, default='', max_length=250, verbose_name='Slug')),
                ('name', models.CharField(default='', max_length=250, verbose_name='Name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtercategories', to='infoshop.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Filter Category',
                'verbose_name_plural': 'Filters Category',
            },
        ),
        migrations.CreateModel(
            name='FilterSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Порядок')),
                ('slug', models.CharField(blank=True, default='', max_length=250, verbose_name='Slug')),
                ('url', models.CharField(blank=True, default='', max_length=250, verbose_name='Url')),
                ('name', models.CharField(default='', max_length=250, verbose_name='Name')),
                ('filter_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filterselect', to='filters.FilterCategory', verbose_name='Filter Category')),
            ],
            options={
                'verbose_name': 'Filter Select',
                'verbose_name_plural': 'Filters Select',
            },
        ),
        migrations.CreateModel(
            name='ProductFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Порядок')),
                ('filter_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_select_product', to='filters.FilterCategory', verbose_name='Filter Category')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filterproducts', to='infoshop.Product', verbose_name='Product')),
                ('values', models.ManyToManyField(blank=True, related_name='filtervalues', to='filters.FilterSelect', verbose_name='Values')),
            ],
            options={
                'verbose_name': 'Product Filter',
                'verbose_name_plural': 'Product Filters',
            },
        ),
    ]
