# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-12 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filtercategory',
            old_name='menutitle',
            new_name='title_menu',
        ),
    ]
