# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-12 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0002_auto_20190512_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtercategory',
            name='seo_description',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='SEO описание'),
        ),
    ]
