# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-19 02:52
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0003_auto_20190512_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtercategory',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контент'),
        ),
    ]
