# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infoshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Порядок')),
                ('value', models.CharField(default='', max_length=250, verbose_name='Значение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_product', to='infoshop.Product', verbose_name='Инфопродукт')),
            ],
            options={
                'verbose_name': 'Характеристика инфопродукта',
                'verbose_name_plural': 'Характеристики инфопродуктов',
            },
        ),
        migrations.CreateModel(
            name='TypeProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Порядок')),
                ('name', models.CharField(default='', max_length=250, verbose_name='Название')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_property', to='infoshop.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Характеристика категории',
                'verbose_name_plural': 'Характеристики категорий',
            },
        ),
        migrations.AddField(
            model_name='productproperty',
            name='type_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_property', to='properties.TypeProperty', verbose_name='Характеристика'),
        ),
    ]
