# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-23 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oko_schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('owner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='oko_schools.Owner')),
                ('name_nominative', models.CharField(max_length=250, null=True, verbose_name='Именительный падеж')),
                ('name_genitive', models.CharField(max_length=250, null=True, verbose_name='Родительный падеж')),
                ('name_dative', models.CharField(max_length=250, null=True, verbose_name='Дательный падеж')),
                ('name_accusative', models.CharField(max_length=250, null=True, verbose_name='Винительный падеж')),
                ('name_ablative', models.CharField(max_length=250, null=True, verbose_name='Творительный падеж')),
                ('name_prepositional', models.CharField(max_length=250, null=True, verbose_name='Предложный падеж')),
                ('education', models.CharField(blank=True, max_length=500, null=True, verbose_name='Образование')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oko_schools.School', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
            bases=('oko_schools.owner', models.Model),
        ),
    ]
